project:
  type: book

book:
  favicon: public/images/logo_dunin.png
  title: "Mandat dunin "
  author: "simon-pierre Beugré"
  date: "2025-05-12"
  chapters:
    - index.qmd
    - part: "Contexte et projet"
      chapters:
        - 01_project_context/index.qmd
    - part: "Analyse exploratoire des données (EDA)  "
      chapters:
          - 03_eda/data_wrangling.qmd
          - 03_eda/descriptive_statistics/orders.qmd 
      
  sidebar: 
    border: true
    logo: public/images/logo_dunin.png     

bibliography: references.bib
format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual
